### ISSUE TITLE
keras原生读权重报错与Exception报错

### ISSUE THREAD

**Issue by riciche** [CalayZhou/MBNet#19]
作者您好，我在训练时遇到了这样的问题，keras在读取权重会报如下错误：

Traceback (most recent call last):
  File "train.py", line 42, in <module>
    model.train_MBNet(C, weight_path, out_path)
  File "/media/love208/DATA/MBNet/keras_MBNet/model/MBNetModel.py", line 54, in train_MBNet
    self.model_all.load_weights(weight_path, by_name=True)
  File "/home/love208/.conda/envs/MBNet/lib/python3.6/site-packages/keras/engine/topology.py", line 2620, in load_weights
    load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/home/love208/.conda/envs/MBNet/lib/python3.6/site-packages/keras/engine/topology.py", line 3161, in load_weights_from_hdf5_group_by_name
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

当我把topology.py改为注释代码的两种形式时，模型能加载起来，但会爆与问题１８一样的错误，各种配置与您的参考配置一致
[https://github.com/CalayZhou/MBNet/issues/18](url)

    if 'keras_version' in f.attrs:
        original_keras_version = f.attrs['keras_version'].decode('utf8')
        #original_keras_version = f.attrs['keras_version'].encode('utf8').decode('utf8')
        #original_keras_version = f.attrs['keras_version']            
    else:
        original_keras_version = '1'
    if 'backend' in f.attrs:
        original_backend = f.attrs['backend'].decode('utf8')
        #original_backend = f.attrs['backend'].encode('utf8').decode('utf8')
        #original_backend = f.attrs['backend']

**Comment by CalayZhou** [comment]
您好，请贴一下具体环境，这个问题我之前没有碰到过

**Comment by riciche** [comment]
ubuntu: 16.04
nvidia driver version: 430.14
cuda: 10.0
cudnn: 7.6.5
python: 3.6

Package              Version
-------------------- -------------------
absl-py              0.11.0
astor                0.8.1
cached-property      1.5.2
certifi              2020.6.20
gast                 0.4.0
google-pasta         0.2.0
grpcio               1.33.2
h5py                 3.1.0
importlib-metadata   2.0.0
Keras                2.1.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
Markdown             3.3.3
numpy                1.19.4
opencv-python        4.4.0.46
pip                  20.2.4
protobuf             3.13.0
PyYAML               5.3.1
scipy                1.5.4
setuptools           50.3.1.post20201107
six                  1.15.0
tensorboard          1.14.0
tensorflow-estimator 1.14.0
tensorflow-gpu       1.14.0
termcolor            1.1.0
Werkzeug             1.0.1
wheel                0.35.1
wrapt                1.12.1
zipp                 3.4.0

**Comment by WestHan33** [comment]
> 作者您好，我在训练时遇到了这样的问题，keras在读取权重会报如下错误：
> 
> Traceback (most recent call last):
> File "train.py", line 42, in
> model.train_MBNet(C, weight_path, out_path)
> File "/media/love208/DATA/MBNet/keras_MBNet/model/MBNetModel.py", line 54, in train_MBNet
> self.model_all.load_weights(weight_path, by_name=True)
> File "/home/love208/.conda/envs/MBNet/lib/python3.6/site-packages/keras/engine/topology.py", line 2620, in load_weights
> load_weights_from_hdf5_group_by_name(f, self.layers)
> File "/home/love208/.conda/envs/MBNet/lib/python3.6/site-packages/keras/engine/topology.py", line 3161, in load_weights_from_hdf5_group_by_name
> original_keras_version = f.attrs['keras_version'].decode('utf8')
> AttributeError: 'str' object has no attribute 'decode'
> 
> 当我把topology.py改为注释代码的两种形式时，模型能加载起来，但会爆与问题１８一样的错误，各种配置与您的参考配置一致
> [https://github.com/CalayZhou/MBNet/issues/18](url)
> 
> ```
> if 'keras_version' in f.attrs:
>     original_keras_version = f.attrs['keras_version'].decode('utf8')
>     #original_keras_version = f.attrs['keras_version'].encode('utf8').decode('utf8')
>     #original_keras_version = f.attrs['keras_version']            
> else:
>     original_keras_version = '1'
> if 'backend' in f.attrs:
>     original_backend = f.attrs['backend'].decode('utf8')
>     #original_backend = f.attrs['backend'].encode('utf8').decode('utf8')
>     #original_backend = f.attrs['backend']
> ```
同学您好，我之前也遇到了一样的问题：1. 对于这个“AttributeError: 'str' object has no attribute 'decode'”问题，我当时就是在topology.py文件报错的那一行，“.decode('utf8')”命令前添加“.encode('utf8')”，就解决了，之后可能还会有类似的报错，但是用同一种方法都能解决。2. 对于“Exception: Error when checking target: expected concatenate_2 to have shape (None, 2) but got array with shape (10, 1)。”这个错误，我当时是用的keras=2.1.6版本，我将keras=2.1.6版本删除后，重新装了keras=2.1.0版本，这个问题就解决了。

**Comment by CalayZhou** [comment]
@WestHan33  感谢解答~

**Comment by riciche** [comment]
> > 作者您好，我在训练时遇到了这样的问题，keras在读取权重会报如下错误：
> > Traceback (most recent call last):
> > File "train.py", line 42, in
> > model.train_MBNet(C, weight_path, out_path)
> > File "/media/love208/DATA/MBNet/keras_MBNet/model/MBNetModel.py", line 54, in train_MBNet
> > self.model_all.load_weights(weight_path, by_name=True)
> > File "/home/love208/.conda/envs/MBNet/lib/python3.6/site-packages/keras/engine/topology.py", line 2620, in load_weights
> > load_weights_from_hdf5_group_by_name(f, self.layers)
> > File "/home/love208/.conda/envs/MBNet/lib/python3.6/site-packages/keras/engine/topology.py", line 3161, in load_weights_from_hdf5_group_by_name
> > original_keras_version = f.attrs['keras_version'].decode('utf8')
> > AttributeError: 'str' object has no attribute 'decode'
> > 当我把topology.py改为注释代码的两种形式时，模型能加载起来，但会爆与问题１８一样的错误，各种配置与您的参考配置一致
> > [https://github.com/CalayZhou/MBNet/issues/18](url)
> > ```
> > if 'keras_version' in f.attrs:
> >     original_keras_version = f.attrs['keras_version'].decode('utf8')
> >     #original_keras_version = f.attrs['keras_version'].encode('utf8').decode('utf8')
> >     #original_keras_version = f.attrs['keras_version']            
> > else:
> >     original_keras_version = '1'
> > if 'backend' in f.attrs:
> >     original_backend = f.attrs['backend'].decode('utf8')
> >     #original_backend = f.attrs['backend'].encode('utf8').decode('utf8')
> >     #original_backend = f.attrs['backend']
> > ```
> 
> 同学您好，我之前也遇到了一样的问题：1. 对于这个“AttributeError: 'str' object has no attribute 'decode'”问题，我当时就是在topology.py文件报错的那一行，“.decode('utf8')”命令前添加“.encode('utf8')”，就解决了，之后可能还会有类似的报错，但是用同一种方法都能解决。2. 对于“Exception: Error when checking target: expected concatenate_2 to have shape (None, 2) but got array with shape (10, 1)。”这个错误，我当时是用的keras=2.1.6版本，我将keras=2.1.6版本删除后，重新装了keras=2.1.0版本，这个问题就解决了。

感谢解答

**Comment by XueZ-phd** [comment]
您好，我也遇到“Exception: Error when checking target: expected concatenate_2 to have shape (None, 2) but got array with shape (10, 1)”的问题。根据之前的issue，我可以确保keras=2.1.0，但是仍然报错。下面是我的环境：

> absl-py @ file:///opt/conda/conda-bld/absl-py_1639803114343/work
astor==0.8.1
certifi==2016.2.28
gast @ file:///tmp/build/80754af9/gast_1637837472536/work
google-pasta @ file:///Users/ktietz/demo/mc3/conda-bld/google-pasta_1630577991354/work
grpcio==1.12.1
h5py==2.8.0
Keras==2.1.0
Keras-Applications @ file:///tmp/build/80754af9/keras-applications_1594366238411/work
Keras-Preprocessing @ file:///tmp/build/80754af9/keras-preprocessing_1612283640596/work
Markdown==2.6.9
mkl-fft==1.3.0
mkl-random==1.1.1
mkl-service==2.3.0
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1603487797006/work
opencv-python==4.5.5.64
protobuf==3.17.2
PyYAML==6.0
scipy @ file:///tmp/build/80754af9/scipy_1597686625380/work
six==1.10.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
Werkzeug==0.12.2
wrapt==1.12.1
